# Generated by Django 5.2.2 on 2025-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
