FROM ghcr.io/osgeo/gdal:ubuntu-full-3.9.2

ENV PYTHONUNBUFFERED=1

# Install Python and Postgres support
RUN apt-get update && apt-get install -y \
    python3 python3-venv python3-pip \
    libpq-dev gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Set up virtual environment
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

RUN ln -sf /usr/lib/x86_64-linux-gnu/libgdal.so.35 /usr/lib/libgdal.so.30 \
 && ldconfig

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]